### ISSUE TITLE
What does "must not be larger than 64 KiB" means?

### ISSUE THREAD

**Issue by deendayal-garg** [hola/challenge_word_classifier#1]
does it mean that my file size should not be greater than 64 KiB or does it mean that i am not allowed to use more than 64 KiB memory? sorry if the question sounds stupid.

**Comment by feldgendler** [comment]
“Your JS file must not be larger than 64 KiB.”

This refers to the size of your JS file. Memory use is not restricted, other than by the default Node.js settings.
