### ISSUE TITLE
dictionary file read

### ISSUE THREAD

**Issue by ichyr** [hola/challenge_word_classifier#2]
Where this `words.txt` would be located relative to our application file, so the application script can require it to parse?

**Comment by DDuarte** [comment]
> > init(data)


> This export is optional. If supplied, it will be called once to initialize your module. The data argument will contain your extra data file (see below) as a Buffer, or undefined if you don't supply a data file.

**Comment by thanhlmm** [comment]
> This export is optional. If supplied, it will be called once to initialize your module. The data argument will contain your **extra data** file (see below) as a Buffer, or undefined if you don't supply a data file.

It's personal data dude, how can we load words.txt with out using required("fs");

**Comment by avs20** [comment]
@ichyr I don't think that words.txt file will be available to scripts. Otherwise it will be just look up and tell the answer. I think we have to somehow compress the words.txt file into 64kb ,

**Comment by feldgendler** [comment]
words.txt is not available to your program. If you could compress it into 64 KiB, you would achieve 100% correctness, but we don't really think it's possible. Almost certainly, you'll have to settle for a correctness rate under 100%.

**Comment by avs20** [comment]
@feldgendler  Yes, that will be very difficult to compress 6mb into <64kb and that's the real challenge.
