### ISSUE TITLE
Clarify case-sensitivity

### ISSUE THREAD

**Issue by AlexanderOMara** [hola/challenge_word_classifier#5]
The instructions say:

> Membership in the dictionary is case-insensitive.

However it's not entirely clear what this means. The list contains for example `ZZZ`, `Zzz`, and `zzz`.

Should a 100% accurate implementation check the case-sensitivity? For example, would input of `zZz` fail or pass?

**Comment by sophiebits** [comment]
I believe it would pass. One of the test cases I downloaded says "tylosurus" should pass yet only "Tylosurus" is in the dictionary. The fact that zzz appears three times is probably an ignorable curiosity.

**Comment by feldgendler** [comment]
A string W is considered an English word if and only if words.txt contains at least one string S where W.toLowerCase()==S.toLowerCase().
